###
# @name: Register
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json
X-Api-Key: 9mzegA8S.fwwakSHeZyrL50IfYd2TNEjHLTwjX7l5

{
  "username": "uername5",
  "email": "user5@example.com",
  "password": "password1"
}

###
# @name: Login
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json
X-Api-Key: 9mzegA8S.fwwakSHeZyrL50IfYd2TNEjHLTwjX7l5

###
# @name: Retrive Short link URL
GET http://localhost:8000/api/v1/url/1L9zO9O
Accept: application/json
X-Api-Key: 9mzegA8S.fwwakSHeZyrL50IfYd2TNEjHLTwjX7l5

###
# @name: Test short link generator
POST http://localhost:8000/api/v1/url
Content-Type: application/json
X-Api-Key: 9mzegA8S.fwwakSHeZyrL50IfYd2TNEjHLTwjX7l5

{
  "long_url": "https://medium.com/@aarav.gupta9/simple-url-shortener-using-python-d433c2464062"
}

###
# @name: List all genrerated urls
GET http://localhost:8000/api/v1/url
Accept: application/json
X-Api-Key: 9mzegA8S.fwwakSHeZyrL50IfYd2TNEjHLTwjX7l5





