name: Build Django API

on:
  push:
    branches:
      - main
    paths:
      - "!web/**"
      - ".github/workflows/BuildApi.yml"
  pull_request:
    branches:
      - main
    paths:
      - "!web/**"
      - ".github/workflows/BuildApi.yml"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Python 3.9
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: Run tests
          run: |
              python manage.py test