name: Build Django API

on:
  push:
    branches:
      - main
    paths-ignore:
      - "web/**"
      - ".github/workflows/BuildWeb.yml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "web/**"
      - ".github/workflows/BuildWeb.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install

      - name: Run tests
        run: |
          python manage.py test